/* Database schema to keep the structure of entire database. */

CREATE TABLE animals(
	id   			INT				GENERATED BY DEFAULT AS IDENTITY,
	name 			VARCHAR			NOT NULL,
	date_of_birth	DATE			NOT NULL,
	escape_attempts	INT,
	neutered   		BOOLEAN,
	weight_kg		DECIMAL (18, 2),
	PRIMARY KEY (ID)
);

ALTER TABLE animals
  ADD species VARCHAR;