/* Database schema to keep the structure of entire database. */

CREATE TABLE animals(
	id   			INT				GENERATED BY DEFAULT AS IDENTITY,
	name 			VARCHAR			NOT NULL,
	date_of_birth	DATE			NOT NULL,
	escape_attempts	INT,
	neutered   		BOOLEAN,
	weight_kg		DECIMAL (18, 2),
	PRIMARY KEY (ID)
);

ALTER TABLE animals
  ADD species VARCHAR;

CREATE TABLE owners (
    id SERIAL PRIMARY KEY,
    full_name varchar(255),
    age integer
);

CREATE TABLE species (
    id SERIAL PRIMARY KEY,
    name varchar(255)
);

ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals 
  ADD species_id INTEGER REFERENCES species(id);

ALTER TABLE animals
  ADD owner_id INTEGER REFERENCES owners(id);   

